.TH "QwtPolarPanner" 3 "Fri Sep 19 2014" "Version 1.1.1" "Qwt Polar User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPolarPanner \- 
.PP
\fBQwtPolarPanner\fP provides panning of a polar plot canvas\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_polar_panner\&.h>\fP
.PP
Inherits QwtPanner\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPolarPanner\fP (\fBQwtPolarCanvas\fP *)"
.br
.RI "\fICreate a plot panner for a polar plot canvas\&. \fP"
.ti -1c
.RI "virtual \fB~QwtPolarPanner\fP ()"
.br
.RI "\fIDestructor\&. \fP"
.ti -1c
.RI "\fBQwtPolarPlot\fP * \fBplot\fP ()"
.br
.ti -1c
.RI "const \fBQwtPolarPlot\fP * \fBplot\fP () const "
.br
.ti -1c
.RI "\fBQwtPolarCanvas\fP * \fBcanvas\fP ()"
.br
.ti -1c
.RI "const \fBQwtPolarCanvas\fP * \fBcanvas\fP () const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBmovePlot\fP (int dx, int dy)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwidgetMousePressEvent\fP (QMouseEvent *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQwtPolarPanner\fP provides panning of a polar plot canvas\&. 

\fBQwtPolarPanner\fP is a panner for a \fBQwtPolarCanvas\fP, that adjusts the visible area after dropping the canvas on its new position\&.
.PP
Together with \fBQwtPolarMagnifier\fP individual ways of navigating on a \fBQwtPolarPlot\fP widget can be implemented easily\&.
.PP
\fBSee Also:\fP
.RS 4
\fBQwtPolarMagnifier\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBQwtPolarCanvas\fP * QwtPolarPanner::canvas ()"

.PP
\fBReturns:\fP
.RS 4
observed plot canvas 
.RE
.PP

.SS "const \fBQwtPolarCanvas\fP * QwtPolarPanner::canvas () const"

.PP
\fBReturns:\fP
.RS 4
observed plot canvas 
.RE
.PP

.SS "void QwtPolarPanner::movePlot (intdx, intdy)\fC [protected]\fP, \fC [virtual]\fP, \fC [slot]\fP"
Adjust the zoomed area according to dx/dy
.PP
\fBParameters:\fP
.RS 4
\fIdx\fP Pixel offset in x direction 
.br
\fIdy\fP Pixel offset in y direction
.RE
.PP
\fBSee Also:\fP
.RS 4
QwtPanner::panned(), \fBQwtPolarPlot::zoom()\fP 
.RE
.PP

.SS "\fBQwtPolarPlot\fP * QwtPolarPanner::plot ()"

.PP
\fBReturns:\fP
.RS 4
observed plot 
.RE
.PP

.SS "const \fBQwtPolarPlot\fP * QwtPolarPanner::plot () const"

.PP
\fBReturns:\fP
.RS 4
observed plot 
.RE
.PP

.SS "void QwtPolarPanner::widgetMousePressEvent (QMouseEvent *event)\fC [protected]\fP, \fC [virtual]\fP"
Block panning when the plot zoom factor is >= 1\&.0\&.
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP Mouse event 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt Polar User's Guide from the source code\&.
